### ISSUE TITLE
Add a blacklist of known problematic functions?

### ISSUE THREAD

**Issue by AlexWaygood** [JelleZijlstra/stubdefaulter#36]
Currently, every time we run `stubdefaulter` on the stdlib, we have to manually revert several changes that are incorrect. For example, `stubdefaulter` always tries to add a default value to the `scheme` parameter of `sysconfig.get_path`, even though _we_ know that the default parameter is [dynamically determined by a function call](https://github.com/python/cpython/blob/0ef92d979311ba82d4c41b22ef38e12e1b08b13d/Lib/sysconfig.py#L631-L636), and varies depending on the machine you're running on.

`types.CodeType.replace` is problematic for a different reason. The signature at runtime is the following:

```pycon
>>> import types
>>> import inspect
>>> inspect.signature(types.CodeType.replace)
<Signature (self, /, *, co_argcount=-1, co_posonlyargcount=-1, co_kwonlyargcount=-1, co_nlocals=-1, co_stacksize=-1, co_flags=-1, co_firstlineno=-1, co_code=None, co_consts=None, co_names=None, co_varnames=None, co_freevars=None, co_cellvars=None, co_filename=None, co_name=None, co_linetable=None)>
```

But the signature given by `inspect.signature` is misleading. If you actually try to supply `None` to any of the `None`-defaulting parameters, the function raises:

```pycon
>>> def foo(): ...
... 
>>> c = foo.__code__
>>> c.replace(co_code=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: replace() argument 'co_code' must be bytes, not None
```

I think [typeshed's signature](https://github.com/python/typeshed/blob/dd3aedd1332c8c6515e6b093714ec24188e8efe8/stdlib/types.pyi#L241-L262) for `types.CodeType.replace` should probably just be left as it is, but every time you run stubdefaulter on typeshed, it tries to add `None` as a default value for each parameter where `inspect.signature` gives `None` as the default value.

As we continue to expand the scope of `stubdefaulter`, we'll come across more and more cases like this, and it'll get more and more tedious to manually revert them every time we do a `stubdefaulter` PR to typeshed. Maybe we should have a blacklist of functions that are known to be problematic, and should be skipped? What do you think?

**Comment by JelleZijlstra** [comment]
Makes sense! I'd suggest an implementation something like this:
- stubdefaulter supports an option to pass a file containing lines of the form `types.CodeType.replace`; each of those functions will be ignored
- In this repo we maintain a blacklist file for the stdlib, that will be used automatically by default when you run stubdefaulter on the stdlib.
- For running on third-party stubs, users can pass their own blacklist files.

**Comment by AlexWaygood** [comment]
Nice, that sounds like a plan!
