### ISSUE TITLE
Crash if not installed in editable mode

### ISSUE THREAD

**Issue by hamdanal** [JelleZijlstra/stubdefaulter#60]
**Description:**

When installed with `pip install path/to/stubdefaulter/repo`, `stubdefaulter` crashes on this line. 
https://github.com/JelleZijlstra/stubdefaulter/blob/afee42c3a783f0bd92179691653d4ca12f1d56f3/stubdefaulter.py#L550
This is because the file `stdlib-blacklist.txt` is not packaged in the distribution that gets installed with the pip command above.

**Workaround:**

Install in *editable mode* `pip install -e path/to/stubdefaulter/repo`. In this case `stubdefaulter` is invoked in-tree from the git clone where the `stdlib-blacklist.txt` file exists.

**Solution:**

Any of:
1. package the `stdlib-blacklist.txt` file with the project;
2. change the usage entry in the README from `pip install .` to `pip install -e .`
3. do nothing, this is not a supported.

**Comment by JelleZijlstra** [comment]
Thanks for reporting! Let's do your solution 1.
