### ISSUE TITLE
Don't add ridiculously long defaults

### ISSUE THREAD

**Issue by AlexWaygood** [JelleZijlstra/stubdefaulter#67]
We shouldn't establish too many rules about exactly which defaults are stylistically acceptable and which aren't (because that's `flake8-pyi`'s job), but I think it would be useful if we skipped adding defaults where the repr of the default is, say, >100 characters long. (We can debate exactly what number we want.) Extremely long defaults are probably not wanted by any users of stubdefaulter; and they can cause mypy, flake8, IDLE and black to hang in some situations (e.g. https://github.com/psf/black/issues/3627; https://github.com/python/cpython/issues/103089; https://github.com/python/mypy/issues/14970).

What do you think?

**Comment by JelleZijlstra** [comment]
Makes sense, though I'd put the limit bigger, say at 1000.

Ideally I'd not use the length of the repr() as the limit, but the complexity of the AST, say by counting the total number of AST nodes.
